name: splendid_code_quality
description: A Dart CLI tool for analyzing and measuring code quality using industry-standard metrics.
version: 1.0.1
repository: https://github.com/Toglefritz/splendid_code_quality

executables:
  splendid_code_quality: splendid_code_quality

environment:
  sdk: ^3.10.7

dependencies:
  analyzer: ^13.3.0
  args: ^2.7.0
  pubspec_parse: ^1.5.0

dev_dependencies:
  test: ^1.25.6
  very_good_analysis: ^10.1.0
